seed: 42
data:
  tickers: [AAPL]
  interval: 1d
  window: 64
  horizon: 1
  target_col: close
  feature_set: default
  data_dir: data/processed
training:
  batch_size: 64
  lr: 1e-3
  epochs: 5
  grad_clip: 1.0
  ckpt_dir: experiments/checkpoints
model:
  type: bnn_vi_pyro
  hidden_size: 128
  num_layers: 2
  prior_scale: 0.1
mlflow:
  tracking_uri: ./mlruns
  experiment_name: bnn_vi

